services:
  - type: web
    name: plc-ai-assistant
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: plc-assistant-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_KEY
        value: plc-admin-2024

databases:
  - name: plc-assistant-db
    databaseName: plc_assistant
    user: plc_user
    plan: free